export default Object.freeze({
  ACCOUNT: "Account",
  ACCOUNT_SCREEN: "AccountScreen",
  COOKBOOKS: "Cookbooks",
  COOKBOOKS_SCREEN: "CookbooksScreen",
  COOKBOOK_DETAILS: "Cookbook Details",
  HOME: "Home",
  HOME_SCREEN: "HomeScreen",
  INVENTORY: "Inventory",
  INVENTORY_SCREEN: "InventoryScreen",
  LOGIN: "Login",
  MAIN: "Main",
  MAINTENANCE: "Maintenance",
  MAINTENANCE_SCREEN: "MaintenanceScreen",
  MEAL_PLANNER: "Meal Planner",
  MEAL_PLANNER_SCREEN: "MealPlannerScreen",
  MEAL_PLAN: "Meal Plan",
  MY_LISTS: "My Lists",
  MY_LISTS_SCREEN: "MyListScreen",
  PROJECTS: "Projects",
  PROJECTS_SCREEN: "ProjectsScreen",
  PROJECT_LIST: "Project List",
  RECIPE_BOX: "Recipe Box",
  RECIPE_CREATE: "Recipe Create",
  RECIPE_DETAILS: "Recipe Details",
  REGISTER: "Register",
  SHOPPING_HOME: "Shopping Home",
  SHOPPING_HOME_SCREEN: "ShoppingHomeScreen",
  SHOPPING_LIST: "Shopping List",
  TODO: "Todo List",
  WELCOME: "Welcome",
});
